<div class="container app d-flex justify-content-center">
    <div class="page">
        <h3 class="text-success">Sign Up</h3>
        <form class="form-group" action="/auth_signup" method="post">
            <label>Name:</label><br>
            <input class="form-control" type="text" name="name">
            <label>Email:</label><br>
            <input class="form-control" type="email" name="email">
            <label>Password:</label><br>
            <input class="form-control" type="password" name="password">

            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-success">Sign Up</button>
            </div>
        </form>
        <hr>
        <div class="lead d-flex justify-content-center little-small">Already have an account?</div>
        <br>
        <div class="d-flex justify-content-center">
            <a href="/" class="btn btn-info">Login</a>
        </div>
    </div>
</div>