<?php if(!empty($this->view->warning)) { ?>

    <div class="text-center bg-warning text-light mb-4">
        You cannot have more than 2 books
    </div>

<?php }; ?>

<div class="row">

    <div class="col-sm-3">
        <a href="#">
            <img class="img-fluid list-img mx-auto d-block" src="<?= $this->view->book['image_link'] ?>" alt="cover">
        </a>
    </div>
    <div class="col-sm-9">
        <a href="#"><?= $this->view->book['title'] ?></a>
        <br>

        <small><?= $this->view->book['author'] ?>-<?= $this->view->book['published_at'] ?></small>
        <br><br>

        <span><?= $this->view->book['description'] ?></span>
        <br><br>
        
        <small>Genres: <?= $this->view->book['genres'] ?></small>
        <br>
        
        <small>Pages: <?= $this->view->book['pages'] ?></small>
    </div>

    <div class="col-sm-12 text-center mt-3">

        <?php if($this->view->requested == true) { ?>

            <a href="/remove_request?id=<?= $this->view->book['id'] ?>" class="btn btn-danger text-white">Remove Request</a>
            
        <?php } elseif($this->view->book['available'] == 1) { ?>
                
                <a href="/request?id=<?= $this->view->book['id'] ?>" class="btn btn-success text-white">Request</a>

        <?php } else { ?>

                <a href="#" class="btn btn-info disabled text-white">This book is not available</a>

        <?php }; ?>

    </div>
    
</div>