<div class="row">

    <?php if(isset($this->view->request) && $this->view->request == false) { ?>

        <div class="col-12 bg-warning text-light text-center mb-2">
            Already Requested
        </div>
        
    <?php } elseif($this->view->request == true) { ?>
            
        <div class="col-12 bg-success text-light text-center mb-2">
            Successfully Requested
        </div>

    <?php }; ?>

    <div class="col-sm-3">
        <a href="#">
            <img class="img-fluid list-img mx-auto d-block" src="<?= $this->view->book['image_link'] ?>" alt="cover">
        </a>
    </div>
    <div class="col-sm-9">
        <a href="#"><?= $this->view->book['title'] ?></a>
        <br>

        <small><?= $this->view->book['author'] ?>-<?= $this->view->book['published_at'] ?></small>
        <br><br>

        <span><?= $this->view->book['description'] ?></span>
        <br><br>
        
        <small>Genres: <?= $this->view->book['genres'] ?></small>
        <br>
        
        <small>Pages: <?= $this->view->book['pages'] ?></small>
    </div>

    <div class="col-sm-12 text-center mt-3">

        <?php if($this->view->request == true) { ?>

            <a href="/remove_request?id=<?= $this->view->book['id'] ?>" class="btn btn-danger text-white">Remove Request</a>
            
        <?php } elseif($this->view->book['available'] == 1) { ?>
                
                <a href="/request?id=<?= $this->view->book['id'] ?>" class="btn btn-success text-white">Request</a>

        <?php } else { ?>

                <a href="#" class="btn btn-info disabled text-white">This book is not available</a>

        <?php }; ?>

    </div>
    
</div>