<?php 

    if(!empty($this->view->books[0]['title'])) {
        foreach($this->view->books as $key => $book) { 
        
?>

    <?php if($key != 0) { ?>

        <hr>

    <?php }; ?>

    <div class="row">
        <div class="col-sm-3">
            <a href="/book_info?id=<?= $book['id'] ?>">
                <img class="img-fluid list-img mx-auto d-block" src="<?= $book['image_link'] ?>" alt="cover">
            </a>
        </div>
        <div class="col-sm-9">
            <a href="/book_info?id=<?= $book['id'] ?>"><?= $book['title'] ?></a>
            <br>

            <small><?= $book['author'] ?>-<?= $book['published_at'] ?></small>
            <br><br>

            <span><?= strlen($book['description']) > 150 ? substr($book['description'], 0, 150) . '...' : $book['description'] ?></span>
            <br><br>
            
            <small>Genres: <?= $book['genres'] ?></small>
            <br>
            
            <small>Pages: <?= $book['pages'] ?></small>
        </div>
    </div>

<?php };} else { ?>

    <div class="text-center text-black-50">
        You do not have any book, try requesting one!
    </div>

<?php }; ?>