<div class="row">
    <div class="col-sm-3">
        <a href="#">
            <img class="img-fluid list-img mx-auto d-block" src="<?= $this->view->book['image_link'] ?>" alt="cover">
        </a>
    </div>
    <div class="col-sm-9">
        <a href="#"><?= $this->view->book['title'] ?></a>
        <br>

        <small><?= $this->view->book['author'] ?>-<?= $this->view->book['published_at'] ?></small>
        <br><br>

        <span><?= $this->view->book['description'] ?></span>
        <br><br>
        
        <small>Genres: <?= $this->view->book['genres'] ?></small>
        <br>
        
        <small>Pages: <?= $this->view->book['pages'] ?></small>
    </div>
</div>