<?php if(!empty($this->view->books[0]['title'])) { 
        foreach($this->view->books as $key => $info) {    
            if($key != 0) echo '<hr>';
?>

    <div class="row">
        <div class="col-sm-9 align-self-center">
            <span><strong><?= $info['name'] ?></strong> currently have:</span>
            <br>

            <em><?= $info['title'] ?></em>
            <br>

            <small><?= $info['author'] ?></small>

            <div class="mt-3">
                <a class="btn btn-danger btn-sm" href="/remove_book_admin?id=<?= $info['id'] ?>&id_user=<?= $info['id_user'] ?>">Remove Book</a>
            </div>
        </div>
        <div class="col-sm-3">
            <img class="img-fluid list-img mx-auto d-block" src="<?= $info['image_link'] ?>" alt="cover">
        </div>
    </div>

<?php }} else { ?>

    <div class="text-center text-black-50">
        No one is currently using a book!
    </div>

<?php } ?>