<div class="row">
    <div class="col-sm-3 request-box mx-3 mb-3 bg-light p-3">
        <div class="text-center">
            <strong>Name</strong> requested:
        </div>

        <div class="text-center my-2">
            <em>Book's Name</em>
        </div>

        <div class="col-sm-13 text-center">
            <a href="#" class="btn btn-info btn-sm text-white">Accept Request</a>
        </div>
    </div>
</div>