<div class="row">

    <?php foreach($this->view->requests as $request) { ?>

        <div class="col-sm-3 request-box mx-3 mb-3 bg-light p-3">
            <div class="text-center">
                <div>
                    <strong><?= $request['name'] ?></strong> requested:
                </div>

                <div class="my-2">
                    <em><?= $request['title'] ?></em>
                </div>

                <form action="/accept_request" method="post">
                    <input type="hidden" name="id_book" value="<?= $request['id'] ?>">
                    <input type="hidden" name="id_user" value="<?= $request['id_user'] ?>">
                    <div class="col-sm-13">
                        <button type="submit" class="btn btn-info btn-sm text-white">Accept Request</button>
                    </div>
                </form>
            </div>
        </div>

    <?php }; ?>

</div>