<?php if(!empty($this->view->requests[0]['name'])) { ?>

    <div class="row">

        <?php foreach($this->view->requests as $request) { ?>

            <div class="col-sm-3 request-box mx-3 mb-3 bg-light py-3">
                <div class="text-center">
                    <div>
                        <strong><?= $request['name'] ?></strong> requested:
                    </div>

                    <div class="my-2">
                        <em class="title"><?= strlen($request['title']) > 26 ? substr($request['title'], 0, 25).'...' : $request['title'] ?></em>
                    </div>

                    
                    <div class="text-center mt-4">
                        <form action="/accept_request" method="post">
                            <input type="hidden" name="id_book" value="<?= $request['id'] ?>">
                            <input type="hidden" name="id_user" value="<?= $request['id_user'] ?>">
                            <button type="submit" class="btn btn-info btn-sm text-white">Accept Request</button>
                        </form>
                        <form action="/reject_request" method="post">
                            <input type="hidden" name="id_book" value="<?= $request['id'] ?>">
                            <input type="hidden" name="id_user" value="<?= $request['id_user'] ?>">
                            <button type="submit" class="btn btn-danger btn-sm text-white">Reject Request</button>
                        </form>
                    </div>
                </div>
            </div>

        <?php }; ?>

    </div>

<?php } else { ?>
    
    <div class="text-center text-black-50">
        There is not any request!
    </div>

<?php } ?>