<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="icon" type ="image/x-icon" href="https://cdn-icons-png.flaticon.com/512/4/4259.png">
		<title>Library Management System</title>

		<link rel="stylesheet" href="css/style.css">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

		<script src="app.js"></script>

	</head>

	<body>
		<nav class="navbar navbar-light bg-light">
			<div class="container">
				<a class="navbar-brand" href="#">
					<img src="https://cdn-icons-png.flaticon.com/512/4/4259.png" width="30" height="30" class="d-inline-block align-top" alt="logo">
					Library Management System
				</a>
				<ul class="navbar-nav ml-auto">
                	<li class="nav-item"><a href="/logoff" class="nav-link">Logoff</a></li>
            	</ul>
			</div>
		</nav>

		<?php if(isset($_GET['error']) && $_GET['error'] == 404) { ?>

			<div class="bg-danger text-center text-light">
				Book was not found
			</div>

		<?php }; ?>

		<div class="container app">
			<div class="row">
				<div class="col-md-3 menu">
					<ul class="list-group">
						<li class="list-group-item <?= $this->view->content == 'available' ? 'active' : '' ?>"><a class="d-block" href="/available">Available</a></li>
						<li class="list-group-item <?= $this->view->content == 'your_books' ? 'active' : '' ?>" ><a class="d-block" href="/your_books">Your Books</a></li>
						<li class="list-group-item <?= $this->view->content == 'all' ? 'active' : '' ?>"><a class="d-block" href="/all">All</a></li>
					</ul>

					<div class="container page mt-4">
						<div class="text-center">
							<h6>Notifications</h6>
						</div>
						<hr>

						<div class="row">
						
							<?php if(isset($this->view->notifications)) { 
									if(!empty($this->view->notifications)) {
										foreach($this->view->notifications as $key =>$not) {
							?>

								<p class="col-sm-10"><?= $key + 1 ?>. <?= $not['notification'] ?></p>

								<div class="col-sm-2 mt-3">
									<a href="/remove_notification?id_not=<?= $not['id_not'] ?>"><i class="fas fa-trash-alt fa-lg text-danger"></i></a>
								</div>

							<?php };} else { ?>

								<div class="col-sm-12 text-center text-black-50">
									You do not have notifications
								</div>

							<?php }} ?>

						</div>

					</div>
				</div>

				<div class="col-md-9">
					<div class="container page">
						<?php $this->content() ?>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>